[package]
name = "p2x-server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
p2x-config = { path = "../../crates/p2x-config" }
p2x-protocol = { path = "../../crates/p2x-protocol" }
clap.workspace = true
futures.workspace = true
libp2p.workspace = true
p2x-net = { path = "../../crates/p2x-net" }
tokio.workspace = true
tracing-subscriber.workspace = true
