[package]
name = "p2x-net"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
p2x-protocol = { path = "../p2x-protocol" }
futures.workspace = true
libp2p.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize.workspace = true
tokio.workspace = true
web-time.workspace = true
